
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "qmrgnlschrtfvenarovh"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "https://app-sandbox.acelabs.co.za", "https://app-sandbox.acelabs.co.za/advertising"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, the user will be logged out once a password reset is complete.
# Reset token lives for one time use, or 24 hours.
jwt_autorefresh = true
# Defaults to true. If set to false, JWT tokens will use normal secured cookies instead of `HttpOnly`
# cookies. This affects the web app and the behavior of the PKCE flow, that is used to share the
# cookies with trusted site components built with the supabase-js package.
secure_cookie = false
# If enabled, the SameSite attribute will be set to 'None'. This enables OAuth signin popup to work
# correctly on different domains.
cookie_options.same_site = "lax"
# The domain to set cookies to. By default this is empty which means the cookie will be set to the
# current domain, including all subdomains. So `app.example.com` will have its cookies set to
# `.example.com`.
# cookie_options.domain = ""

[functions]
[functions.tiktok-ads]
verify_jwt = true
[functions.meta-auth]
verify_jwt = true
[functions.social-profile]
verify_jwt = true
[functions.send-contract]
verify_jwt = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
