// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmrgnlschrtfvenarovh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcmdubHNjaHJ0ZnZlbmFyb3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjMyODQsImV4cCI6MjA2MzEzOTI4NH0.dLizC4t68_9nW5thCD8wk1RDlivVgCF5l7y2YP6KT9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);